In [2]:
import torch

In [80]:
x = torch.rand(5,3)
x

tensor([[0.7099, 0.8021, 0.2855],
        [0.8545, 0.2541, 0.9079],
        [0.1049, 0.3738, 0.4905],
        [0.1984, 0.5105, 0.4735],
        [0.6984, 0.6122, 0.4374]])

In [81]:
y = torch.rand(5,3)
y

tensor([[0.6524, 0.3789, 0.4101],
        [0.9763, 0.5198, 0.3374],
        [0.2961, 0.3501, 0.9418],
        [0.6093, 0.7544, 0.5625],
        [0.4283, 0.1638, 0.6463]])

In [82]:
# 1.1 加法形式一: +
x+y

tensor([[1.3622, 1.1810, 0.6956],
        [1.8308, 0.7739, 1.2453],
        [0.4010, 0.7239, 1.4323],
        [0.8077, 1.2650, 1.0360],
        [1.1267, 0.7760, 1.0837]])

In [83]:
# 1.2 加法形式二: .add()
torch.add(x,y)

tensor([[1.3622, 1.1810, 0.6956],
        [1.8308, 0.7739, 1.2453],
        [0.4010, 0.7239, 1.4323],
        [0.8077, 1.2650, 1.0360],
        [1.1267, 0.7760, 1.0837]])

In [84]:
# 1.3 加法形式三: inplace
# adds x to y
# 注：PyTorch操作inplace版本都有后缀_, 例如x.copy_(y), x.t_()
y.add_(x)
y

tensor([[1.3622, 1.1810, 0.6956],
        [1.8308, 0.7739, 1.2453],
        [0.4010, 0.7239, 1.4323],
        [0.8077, 1.2650, 1.0360],
        [1.1267, 0.7760, 1.0837]])

In [85]:
# 2. 索引
"""
可以使用类似Numpy的索引操作来访问Tensor的一部分，需要注意的是：索引出来的结果与原数据共享内存，
也即修改一个，另一个会跟着修改
"""
z = x[0, :]
z

tensor([0.7099, 0.8021, 0.2855])

In [8]:
z += 1
z

tensor([1.0674, 1.6330, 1.3551])

In [9]:
# 源tensor也被修改了
x[0, :]

tensor([1.0674, 1.6330, 1.3551])

In [86]:
# 3. torch.index_select(input, dim, index), 第二个参数表示从第几维挑选数据，类型为int值；
help(torch.index_select)

Help on built-in function index_select in module torch:

index_select(...)
    index_select(input, dim, index, *, out=None) -> Tensor
    
    Returns a new tensor which indexes the :attr:`input` tensor along dimension
    :attr:`dim` using the entries in :attr:`index` which is a `LongTensor`.
    
    The returned tensor has the same number of dimensions as the original tensor
    (:attr:`input`).  The :attr:`dim`\ th dimension has the same size as the length
    of :attr:`index`; other dimensions have the same size as in the original tensor.
    
    .. note:: The returned tensor does **not** use the same storage as the original
              tensor.  If :attr:`out` has a different shape than expected, we
              silently change it to the correct shape, reallocating the underlying
              storage if necessary.
    
    Args:
        input (Tensor): the input tensor.
        dim (int): the dimension in which we index
        index (IntTensor or LongTensor): the 1-D tensor 

In [87]:
# 4. torch.masked_select(input, mask)
help(torch.masked_select)

Help on built-in function masked_select in module torch:

masked_select(...)
    masked_select(input, mask, *, out=None) -> Tensor
    
    Returns a new 1-D tensor which indexes the :attr:`input` tensor according to
    the boolean mask :attr:`mask` which is a `BoolTensor`.
    
    The shapes of the :attr:`mask` tensor and the :attr:`input` tensor don't need
    to match, but they must be :ref:`broadcastable <broadcasting-semantics>`.
    
    .. note:: The returned tensor does **not** use the same storage
              as the original tensor
    
    Args:
        input (Tensor): the input tensor.
        mask  (BoolTensor): the tensor containing the binary mask to index with
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> x = torch.randn(3, 4)
        >>> x
        tensor([[ 0.3552, -2.3825, -0.8297,  0.3477],
                [-1.2035,  1.2252,  0.5002,  0.6248],
                [ 0.1307, -2.0608,  0.1244,  2.0139]])
   

In [12]:
x = torch.randn(3,4)
print(x)
mask = x.ge(0.5)
print(mask)
torch.masked_select(x, mask)

tensor([[ 0.1128,  0.7819, -0.0697, -1.7305],
        [ 0.3671, -0.9227, -1.1336, -0.0990],
        [ 0.3498, -0.5823, -0.7950,  0.6583]])
tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False,  True]])


tensor([0.7819, 0.6583])

In [88]:
# 5. torch.nonzero(input, as_tuple)
# https://blog.csdn.net/wangxuecheng666/article/details/120639138
# shape为Z*N（Z是非0的数的个数，N为input的维数）
help(torch.nonzero)

Help on built-in function nonzero in module torch:

nonzero(...)
    nonzero(input, *, out=None, as_tuple=False) -> LongTensor or tuple of LongTensors
    
    .. note::
        :func:`torch.nonzero(..., as_tuple=False) <torch.nonzero>` (default) returns a
        2-D tensor where each row is the index for a nonzero value.
    
        :func:`torch.nonzero(..., as_tuple=True) <torch.nonzero>` returns a tuple of 1-D
        index tensors, allowing for advanced indexing, so ``x[x.nonzero(as_tuple=True)]``
        gives all nonzero values of tensor ``x``. Of the returned tuple, each index tensor
        contains nonzero indices for a certain dimension.
    
        See below for more details on the two behaviors.
    
        When :attr:`input` is on CUDA, :func:`torch.nonzero() <torch.nonzero>` causes
        host-device synchronization.
    
    **When** :attr:`as_tuple` **is** ``False`` **(default)**:
    
    Returns a tensor containing the indices of all non-zero elements of
    :att

In [89]:
# 5.1 返回非0数对应的index
x = torch.nonzero(torch.tensor([[[0.6, 0.0, 0.0, 0.0],
                                [0.0, 0.4, 0.5, 0.0],
                                [0.0, 0.0, 1.2, 0.0],
                                [0.0, 0.0, 0.0,-0.4]]]))
x


tensor([[0, 0, 0],
        [0, 1, 1],
        [0, 1, 2],
        [0, 2, 2],
        [0, 3, 3]])

In [15]:
# 5.2返回多维innput中非零的数
x = torch.tensor([[[0.6, 0.0, 0.0, 0.0],
                                [0.0, 0.4, 0.5, 0.0],
                                [0.0, 0.0, 1.2, 0.0],
                                [0.0, 0.0, 0.0,-0.4]]])
x[x.nonzero(as_tuple=True)]

tensor([ 0.6000,  0.4000,  0.5000,  1.2000, -0.4000])

In [16]:
# 5.3返回一维innput中非零的数
x = torch.tensor([5,3])
print(x)
x[x.nonzero(as_tuple=True)]

tensor([5, 3])


tensor([5, 3])

In [90]:
# 6. torch.gather(input, dim, index)
# https://blog.csdn.net/Apikaqiu/article/details/104253080
help(torch.gather)

Help on built-in function gather in module torch:

gather(...)
    gather(input, dim, index, *, sparse_grad=False, out=None) -> Tensor
    
    Gathers values along an axis specified by `dim`.
    
    For a 3-D tensor the output is specified by::
    
        out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
        out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
        out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2
    
    :attr:`input` and :attr:`index` must have the same number of dimensions.
    It is also required that ``index.size(d) <= input.size(d)`` for all
    dimensions ``d != dim``.  :attr:`out` will have the same shape as :attr:`index`.
    Note that ``input`` and ``index`` do not broadcast against each other.
    
    Args:
        input (Tensor): the source tensor
        dim (int): the axis along which to index
        index (LongTensor): the indices of elements to gather
    
    Keyword arguments:
        sparse_grad (bool, optional): I

In [18]:
import torch
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 0, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 2],
        [3, 2]])

In [19]:
torch.gather(a, 0,torch.tensor([8,4,2]))

tensor([8, 4, 2])

In [20]:
b = torch.arange(36).reshape(6,6)
b

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])

In [21]:
torch.gather(b, 0, torch.tensor([[0,3,4],
                                [0,1,2]]))

tensor([[ 0, 19, 26],
        [ 0,  7, 14]])

In [22]:
"""
[[0, 3, 4],
[6, 7,8]]
"""
torch.gather(b, 1, torch.tensor([[0,3,4],
                                [0,1,2]]))

tensor([[0, 3, 4],
        [6, 7, 8]])

In [24]:
c = torch.arange(36).reshape(2,3,6)
c

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]],

        [[18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]]])

In [27]:
torch.gather(c,1, torch.tensor([[[0,0,0],
                   [0,1,2]]]))

tensor([[[ 0,  1,  2],
         [ 0,  7, 14]]])

In [28]:
torch.gather(c,1, torch.tensor([[[0,0,0],
                   [0,1,2]],
                               [[0,0,0],
                   [0,1,2]]]))

tensor([[[ 0,  1,  2],
         [ 0,  7, 14]],

        [[18, 19, 20],
         [18, 25, 32]]])

In [92]:
x

tensor([[0, 0, 0],
        [0, 1, 1],
        [0, 1, 2],
        [0, 2, 2],
        [0, 3, 3]])

In [93]:
x = torch.arange(15)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [94]:
# 7. 用view()来改变Tensor的形状
"""
注意view()返回的新tensor与源Tensor虽然可能有不同的size,但是共享data，也即是更改其中的一个，另外一个也会跟着改变。
（顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变）
"""
y = x.view(15)

In [95]:
y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
z = x.view(-1, 5)

In [97]:
z

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [39]:
z.shape

torch.Size([3, 5])

In [40]:
y.shape

torch.Size([15])

In [41]:
x.shape

torch.Size([15])

In [47]:
# 8. clone().view()
"""
如果我们想返回一个真正的副本（即不共享data内存）该怎么办呢？---clone().view()
pytorch还提供了一个reshape()苦役改变形状，但是此函数并不能保证返回的是其拷贝，
所以不推荐使用.
推荐先用clone创造一个副本然后再使用view
"""
"""
使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor
"""
print(z)
z_cp = z.clone().view(15)
print(z_cp)
z -= 1
print(z)
print(z_cp)


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
tensor([[-1,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


In [51]:
# 9. item()
"""
可以将一个标量转换成一个python number
"""
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.9166])
1.9165549278259277


In [53]:
yy = torch.randn(2,3)
yy

tensor([[-1.6424, -1.8490,  0.2794],
        [ 0.8115, -0.0530, -0.6954]])

In [ ]:
# 10. #######线性代数相关的一些函数##############
"""
trace   对角线元素之和(矩阵的迹)
diag  对角线元素
triu/tril 矩阵的上三角/下三角，可指定偏移量
mm/bmm  矩阵乘法，batch的矩阵乘法
addmm/addbmm/addmv/addr/baddbmm   矩阵运算
t  转置
dot/cross 内积/外积
inverse 求逆矩阵
svd 奇异值分解
"""


In [98]:
help(torch.trace)

Help on built-in function trace in module torch:

trace(...)
    trace(input) -> Tensor
    
    Returns the sum of the elements of the diagonal of the input 2-D matrix.
    
    Example::
    
        >>> x = torch.arange(1., 10.).view(3, 3)
        >>> x
        tensor([[ 1.,  2.,  3.],
                [ 4.,  5.,  6.],
                [ 7.,  8.,  9.]])
        >>> torch.trace(x)
        tensor(15.)



In [99]:
"""
input是一维，output就是二维， input是二维，则output是一维
"""
help(torch.diag)

Help on built-in function diag in module torch:

diag(...)
    diag(input, diagonal=0, *, out=None) -> Tensor
    
    - If :attr:`input` is a vector (1-D tensor), then returns a 2-D square tensor
      with the elements of :attr:`input` as the diagonal.
    - If :attr:`input` is a matrix (2-D tensor), then returns a 1-D tensor with
      the diagonal elements of :attr:`input`.
    
    The argument :attr:`diagonal` controls which diagonal to consider:
    
    - If :attr:`diagonal` = 0, it is the main diagonal.
    - If :attr:`diagonal` > 0, it is above the main diagonal.
    - If :attr:`diagonal` < 0, it is below the main diagonal.
    
    Args:
        input (Tensor): the input tensor.
        diagonal (int, optional): the diagonal to consider
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    .. seealso::
    
            :func:`torch.diagonal` always returns the diagonal of its input.
    
            :func:`torch.diagflat` always constructs a tens

In [100]:
help(torch.triu)

Help on built-in function triu in module torch:

triu(...)
    triu(input, diagonal=0, *, out=None) -> Tensor
    
    Returns the upper triangular part of a matrix (2-D tensor) or batch of matrices
    :attr:`input`, the other elements of the result tensor :attr:`out` are set to 0.
    
    The upper triangular part of the matrix is defined as the elements on and
    above the diagonal.
    
    The argument :attr:`diagonal` controls which diagonal to consider. If
    :attr:`diagonal` = 0, all elements on and above the main diagonal are
    retained. A positive value excludes just as many diagonals above the main
    diagonal, and similarly a negative value includes just as many diagonals below
    the main diagonal. The main diagonal are the set of indices
    :math:`\lbrace (i, i) \rbrace` for :math:`i \in [0, \min\{d_{1}, d_{2}\} - 1]` where
    :math:`d_{1}, d_{2}` are the dimensions of the matrix.
    
    Args:
        input (Tensor): the input tensor.
        diagonal (int, opt

In [101]:
help(torch.tril)

Help on built-in function tril in module torch:

tril(...)
    tril(input, diagonal=0, *, out=None) -> Tensor
    
    Returns the lower triangular part of the matrix (2-D tensor) or batch of matrices
    :attr:`input`, the other elements of the result tensor :attr:`out` are set to 0.
    
    The lower triangular part of the matrix is defined as the elements on and
    below the diagonal.
    
    The argument :attr:`diagonal` controls which diagonal to consider. If
    :attr:`diagonal` = 0, all elements on and below the main diagonal are
    retained. A positive value includes just as many diagonals above the main
    diagonal, and similarly a negative value excludes just as many diagonals below
    the main diagonal. The main diagonal are the set of indices
    :math:`\lbrace (i, i) \rbrace` for :math:`i \in [0, \min\{d_{1}, d_{2}\} - 1]` where
    :math:`d_{1}, d_{2}` are the dimensions of the matrix.
    
    Args:
        input (Tensor): the input tensor.
        diagonal (int, o

In [70]:
"""
mm/bmm  矩阵乘法，batch的矩阵乘法
addmm/addbmm/addmv/addr/baddbmm   矩阵运算
t  转置
dot/cross 内积/外积
inverse 求逆矩阵
svd 奇异值分解
"""
# 数学上的矩阵相乘
help(torch.mm)

Help on built-in function mm in module torch:

mm(...)
    mm(input, mat2, *, out=None) -> Tensor
    
    Performs a matrix multiplication of the matrices :attr:`input` and :attr:`mat2`.
    
    If :attr:`input` is a :math:`(n \times m)` tensor, :attr:`mat2` is a
    :math:`(m \times p)` tensor, :attr:`out` will be a :math:`(n \times p)` tensor.
    
    .. note:: This function does not :ref:`broadcast <broadcasting-semantics>`.
              For broadcasting matrix products, see :func:`torch.matmul`.
    
    Supports strided and sparse 2-D tensors as inputs, autograd with
    respect to strided inputs.
    
    This operator supports :ref:`TensorFloat32<tf32_on_ampere>`.
    
    On certain ROCm devices, when using float16 inputs this module will use :ref:`different precision<fp16_on_mi200>` for backward.
    
    Args:
        input (Tensor): the first matrix to be matrix multiplied
        mat2 (Tensor): the second matrix to be matrix multiplied
    
    Keyword args:
        out

In [103]:
mat1 = torch.randn(2, 3)
mat1

tensor([[ 0.2621,  2.3984, -1.6417],
        [ 0.9421,  0.0194, -0.1172]])

In [104]:
mat2 = torch.randn(3, 2)
mat2

tensor([[ 1.3501, -0.9045],
        [ 1.0299, -0.0246],
        [-0.8473,  0.7765]])

In [105]:
torch.mm(mat1, mat2)

tensor([[ 4.2151, -1.5709],
        [ 1.3911, -0.9436]])

In [74]:
0.5752*1.6299 + 1.2822*2.9772 -0.6495*0.7673

4.256522970000001

In [102]:
"""
mm/bmm  矩阵乘法，batch的矩阵乘法
addmm/addbmm/addmv/addr/baddbmm   矩阵运算
t  转置
dot/cross 内积/外积
inverse 求逆矩阵
svd 奇异值分解
"""
help(torch.bmm)

Help on built-in function bmm in module torch:

bmm(...)
    bmm(input, mat2, *, out=None) -> Tensor
    
    Performs a batch matrix-matrix product of matrices stored in :attr:`input`
    and :attr:`mat2`.
    
    :attr:`input` and :attr:`mat2` must be 3-D tensors each containing
    the same number of matrices.
    
    If :attr:`input` is a :math:`(b \times n \times m)` tensor, :attr:`mat2` is a
    :math:`(b \times m \times p)` tensor, :attr:`out` will be a
    :math:`(b \times n \times p)` tensor.
    
    .. math::
        \text{out}_i = \text{input}_i \mathbin{@} \text{mat2}_i
    
    This operator supports :ref:`TensorFloat32<tf32_on_ampere>`.
    
    On certain ROCm devices, when using float16 inputs this module will use :ref:`different precision<fp16_on_mi200>` for backward.
    
    .. note:: This function does not :ref:`broadcast <broadcasting-semantics>`.
              For broadcasting matrix products, see :func:`torch.matmul`.
    
    Args:
        input (Tensor): the

In [78]:
input = torch.randn(2, 3, 4)
print(f"input:{input}")
mat2 = torch.randn(2, 4, 5)
print(f"mat2:{mat2}")
res = torch.bmm(input, mat2)
print(f"res:{res}")

input:tensor([[[-1.1847,  0.0410, -0.5768,  0.4169],
         [-0.6415, -0.3177, -0.8972, -0.7950],
         [-2.9986,  2.6437, -1.8537,  0.4957]],

        [[-1.2137,  2.3454, -0.1044, -0.6831],
         [ 0.3544,  0.2728,  0.8918,  0.5072],
         [ 0.0171, -1.3940,  1.0164, -0.0145]]])
mat2:tensor([[[ 0.6089,  0.5453, -0.9820,  0.2671, -1.3822],
         [ 0.2006,  0.2895, -0.9884,  2.1604,  2.5285],
         [-1.4788, -2.0407,  0.2791, -0.0694, -0.5121],
         [-0.3281, -1.0097, -0.3885,  0.8986,  0.5167]],

        [[-1.3075, -0.0859,  0.2601,  0.7127, -0.1840],
         [-0.2685, -0.1976, -1.5441, -1.3401,  0.8365],
         [-0.8632, -0.5366,  0.3598, -0.3461, -1.2170],
         [-0.5274, -1.4887,  0.3305, -0.3523,  1.0441]]])
res:tensor([[[ 3.1184e-03,  1.2203e-01,  7.9981e-01,  1.8691e-01,  2.2520e+00],
         [ 1.1333e+00,  2.1919e+00,  1.0024e+00, -1.5099e+00,  1.3191e-01],
         [ 1.2830e+00,  2.4125e+00, -3.7852e-01,  5.4848e+00,  1.2035e+01]],

        [[ 1.4076

In [79]:
(-1.1847) *0.6089  + 0.0410*0.2006 + (-0.5768)*(-1.4788) + 0.4169*(-0.3281)

0.0030477199999999205

In [108]:
help(torch.addmm)

Help on built-in function addmm in module torch:

addmm(...)
    addmm(input, mat1, mat2, *, beta=1, alpha=1, out=None) -> Tensor
    
    Performs a matrix multiplication of the matrices :attr:`mat1` and :attr:`mat2`.
    The matrix :attr:`input` is added to the final result.
    
    If :attr:`mat1` is a :math:`(n \times m)` tensor, :attr:`mat2` is a
    :math:`(m \times p)` tensor, then :attr:`input` must be
    :ref:`broadcastable <broadcasting-semantics>` with a :math:`(n \times p)` tensor
    and :attr:`out` will be a :math:`(n \times p)` tensor.
    
    :attr:`alpha` and :attr:`beta` are scaling factors on matrix-vector product between
    :attr:`mat1` and :attr:`mat2` and the added matrix :attr:`input` respectively.
    
    .. math::
        \text{out} = \beta\ \text{input} + \alpha\ (\text{mat1}_i \mathbin{@} \text{mat2}_i)
    
    If :attr:`beta` is 0, then :attr:`input` will be ignored, and `nan` and `inf` in
    it will not be propagated.
    
    For inputs of type `Flo

In [110]:
M = torch.randn(2, 3)
M

tensor([[-0.3381, -0.6834,  0.4693],
        [ 0.7009, -0.3207, -0.5713]])

In [111]:
mat1 = torch.randn(2, 3)
mat1

tensor([[-0.5324, -0.3905,  0.4314],
        [-1.7555, -0.1326, -0.9685]])

In [112]:
mat2 = torch.randn(3, 3)
mat2

tensor([[ 0.3579,  0.0051,  0.7342],
        [ 0.2459,  2.9872, -0.5393],
        [ 0.2490,  1.2793,  1.5052]])

In [113]:
torch.addmm(M, mat1, mat2)

tensor([[-0.5172, -1.3008,  0.9384],
        [-0.2012, -1.9649, -3.2465]])

In [115]:
(-0.5324)*0.3579 + (-0.3905)*0.2459 + 0.4314*0.2490+(-0.3381)

-0.51725131

In [116]:
help(torch.addbmm)

Help on built-in function addbmm in module torch:

addbmm(...)
    addbmm(input, batch1, batch2, *, beta=1, alpha=1, out=None) -> Tensor
    
    Performs a batch matrix-matrix product of matrices stored
    in :attr:`batch1` and :attr:`batch2`,
    with a reduced add step (all matrix multiplications get accumulated
    along the first dimension).
    :attr:`input` is added to the final result.
    
    :attr:`batch1` and :attr:`batch2` must be 3-D tensors each containing the
    same number of matrices.
    
    If :attr:`batch1` is a :math:`(b \times n \times m)` tensor, :attr:`batch2` is a
    :math:`(b \times m \times p)` tensor, :attr:`input` must be
    :ref:`broadcastable <broadcasting-semantics>` with a :math:`(n \times p)` tensor
    and :attr:`out` will be a :math:`(n \times p)` tensor.
    
    .. math::
        out = \beta\ \text{input} + \alpha\ (\sum_{i=0}^{b-1} \text{batch1}_i \mathbin{@} \text{batch2}_i)
    
    If :attr:`beta` is 0, then :attr:`input` will be ignored,

In [121]:
# addbmm(input, batch1, batch2)会将batch1和batch2乘起来之后然后相加，之后再和input相加起来

M = torch.ones(3, 2)
print(f"M:{M}")
batch1 = torch.ones(2, 3, 2)
print(f"batch1:{batch1}")
batch2 = torch.ones(2, 2, 2)
print(f"batch2:{batch2}")
torch.addbmm(M, batch1, batch2)

M:tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
batch1:tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
batch2:tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


tensor([[5., 5.],
        [5., 5.],
        [5., 5.]])

In [122]:
torch.bmm(batch1, batch2)

tensor([[[2., 2.],
         [2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.],
         [2., 2.]]])

In [123]:
help(torch.addmv)

Help on built-in function addmv in module torch:

addmv(...)
    addmv(input, mat, vec, *, beta=1, alpha=1, out=None) -> Tensor
    
    Performs a matrix-vector product of the matrix :attr:`mat` and
    the vector :attr:`vec`.
    The vector :attr:`input` is added to the final result.
    
    If :attr:`mat` is a :math:`(n \times m)` tensor, :attr:`vec` is a 1-D tensor of
    size `m`, then :attr:`input` must be
    :ref:`broadcastable <broadcasting-semantics>` with a 1-D tensor of size `n` and
    :attr:`out` will be 1-D tensor of size `n`.
    
    :attr:`alpha` and :attr:`beta` are scaling factors on matrix-vector product between
    :attr:`mat` and :attr:`vec` and the added tensor :attr:`input` respectively.
    
    .. math::
        \text{out} = \beta\ \text{input} + \alpha\ (\text{mat} \mathbin{@} \text{vec})
    
    If :attr:`beta` is 0, then :attr:`input` will be ignored, and `nan` and `inf` in
    it will not be propagated.
    
    For inputs of type `FloatTensor` or `Doub

In [124]:
M = torch.randn(2)
print(f"M:{M}")
mat  = torch.randn(2, 3)
print(f"mat:{mat}")
vec = torch.randn(3)
print(f"vec:{vec}")
torch.addmv(M, mat, vec)

M:tensor([-0.3752, -0.6982])
mat:tensor([[ 1.8442,  0.9186,  0.6109],
        [-2.8610, -0.9939,  0.7575]])
vec:tensor([-0.9267, -1.0354, -1.0850])


tensor([-3.6983,  2.1605])

In [126]:
torch.mv(mat, vec) + torch.tensor([-0.3752, -0.6982])

tensor([-3.6983,  2.1604])

In [128]:
help(torch.mv)

Help on built-in function mv in module torch:

mv(...)
    mv(input, vec, *, out=None) -> Tensor
    
    Performs a matrix-vector product of the matrix :attr:`input` and the vector
    :attr:`vec`.
    
    If :attr:`input` is a :math:`(n \times m)` tensor, :attr:`vec` is a 1-D tensor of
    size :math:`m`, :attr:`out` will be 1-D of size :math:`n`.
    
    .. note:: This function does not :ref:`broadcast <broadcasting-semantics>`.
    
    Args:
        input (Tensor): matrix to be multiplied
        vec (Tensor): vector to be multiplied
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> mat = torch.randn(2, 3)
        >>> vec = torch.randn(3)
        >>> torch.mv(mat, vec)
        tensor([ 1.0404, -0.6361])



In [3]:
# https://blog.csdn.net/qq_41845478/article/details/107490718
# mat*(vec.t)
import torch
mat  = torch.randn(2, 3)
print(f"mat:{mat}")
vec = torch.randn(3)
print(f"vec:{vec}")
torch.mv( mat, vec)

mat:tensor([[ 1.0031,  0.5251,  0.2597],
        [ 0.4389, -1.0294, -1.1313]])
vec:tensor([-0.2550, -1.1652,  0.2843])


tensor([-0.7938,  0.7659])

In [4]:
(-0.2550)*1.0031 + (-1.1652)*0.5251+(0.2597)*(0.2843)

-0.7938043100000001

In [5]:
(-0.2550)*0.4389 + (-1.1652)*(-1.0294)+(-1.1313)*(0.2843)

0.7659087900000001

In [6]:
help(torch.addr)

Help on built-in function addr in module torch:

addr(...)
    addr(input, vec1, vec2, *, beta=1, alpha=1, out=None) -> Tensor
    
    Performs the outer-product of vectors :attr:`vec1` and :attr:`vec2`
    and adds it to the matrix :attr:`input`.
    
    Optional values :attr:`beta` and :attr:`alpha` are scaling factors on the
    outer product between :attr:`vec1` and :attr:`vec2` and the added matrix
    :attr:`input` respectively.
    
    .. math::
        \text{out} = \beta\ \text{input} + \alpha\ (\text{vec1} \otimes \text{vec2})
    
    If :attr:`beta` is 0, then :attr:`input` will be ignored, and `nan` and `inf` in
    it will not be propagated.
    
    If :attr:`vec1` is a vector of size `n` and :attr:`vec2` is a vector
    of size `m`, then :attr:`input` must be
    :ref:`broadcastable <broadcasting-semantics>` with a matrix of size
    :math:`(n \times m)` and :attr:`out` will be a matrix of size
    :math:`(n \times m)`.
    
    Args:
        input (Tensor): matrix to

AttributeError: module 'torch' has no attribute 'r'

In [106]:
# 11. 用方法to()可以将Tensor在CPU和GPU(需要硬件支持)之间相互移动
"""
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型
"""
torch.cuda.is_available()

False

In [58]:
yyy=torch.ones_like(yy)
yyy

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [62]:
zz = yyy.to("cpu", torch.double)
zz

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [3]:
# 内积：又称为点乘， 就是线性代数里面行和列对应元素相乘然后求和。 两向量的内积结果就是标量. torch.dot
# 外积：两个向量的张量积，其结果是一个矩阵。torch.cross
help(torch.dot)

Help on built-in function dot in module torch:

dot(...)
    dot(input, other, *, out=None) -> Tensor
    
    Computes the dot product of two 1D tensors.
    
    .. note::
    
        Unlike NumPy's dot, torch.dot intentionally only supports computing the dot product
        of two 1D tensors with the same number of elements.
    
    Args:
        input (Tensor): first tensor in the dot product, must be 1D.
        other (Tensor): second tensor in the dot product, must be 1D.
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))
        tensor(7)



In [4]:
help(torch.cross)

Help on built-in function cross in module torch:

cross(...)
    cross(input, other, dim=None, *, out=None) -> Tensor
    
    
    Returns the cross product of vectors in dimension :attr:`dim` of :attr:`input`
    and :attr:`other`.
    
    Supports input of float, double, cfloat and cdouble dtypes. Also supports batches
    of vectors, for which it computes the product along the dimension :attr:`dim`.
    In this case, the output has the same batch dimensions as the inputs.
    
    If :attr:`dim` is not given, it defaults to the first dimension found with the
    size 3. Note that this might be unexpected.
    
    .. seealso::
            :func:`torch.linalg.cross` which requires specifying dim (defaulting to -1).
    
    .. warning:: This function may change in a future PyTorch release to match
            the default behaviour in :func:`torch.linalg.cross`. We recommend using
            :func:`torch.linalg.cross`.
    
    Args:
        input (Tensor): the input tensor.
      

In [13]:
# 结果中的每个值是怎么计算得来的，请举例计算出结果中的一个值
from IPython.display import Image
Image(url="cross_matrix.png")


In [16]:
cx = 1.1455 * (-1.2251) - 1.6895 * (-1.4725) # = 1.0844
cy = 1.6895 * (-0.0257) - (-0.3956) * (-1.2251) # = -0.5281
cz = (-0.3956) * (-1.4725) - 1.1455 * (-0.0257) # = 0.6120
print(cx, cy, cz)

1.0844367 -0.52806971 0.6119603499999999


In [12]:
Image(url="cross_formula.png")

In [6]:
from IPython.display import Image
Image(url="cross.png", width=300, height=300)

In [18]:
# 定义两个3D向量
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 计算叉积
c = torch.cross(a, b)
print(c)

"""
cx=12-15=-3
cy=12-6=6
cz=5-8=-3
"""

tensor([-3,  6, -3])


In [19]:
a.T

C:\Users\sunya\AppData\Local\Temp\ipykernel_10872\2533872927.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  C:\b\abs_bao0hdcrdh\croot\pytorch_1675190257512\work\aten\src\ATen\native\TensorShape.cpp:2985.)
  a.T


tensor([1, 2, 3])

In [20]:
a

tensor([1, 2, 3])

In [22]:
torch.cross(a.T, b)

tensor([-3,  6, -3])

In [23]:
# inverse 求逆矩阵
help(torch.inverse)

Help on built-in function inverse in module torch:

inverse(...)
    inverse(input, *, out=None) -> Tensor
    
    Alias for :func:`torch.linalg.inv`



In [24]:
help(torch.dot)

Help on built-in function dot in module torch:

dot(...)
    dot(input, other, *, out=None) -> Tensor
    
    Computes the dot product of two 1D tensors.
    
    .. note::
    
        Unlike NumPy's dot, torch.dot intentionally only supports computing the dot product
        of two 1D tensors with the same number of elements.
    
    Args:
        input (Tensor): first tensor in the dot product, must be 1D.
        other (Tensor): second tensor in the dot product, must be 1D.
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))
        tensor(7)

