In [1]:
"""
线性回归：
1. 输出是一个连续值，适用于回归问题
2. 线性回归和softnax回归都是单层神经网络，它们涉及的概念和技术
    同样适用于大多数的深度学习模型
"""

'\n线性回归：\n1. 输出是一个连续值，适用于回归问题\n2. 线性回归和softnax回归都是单层神经网络，它们涉及的概念和技术\n    同样适用于大多数的深度学习模型\n'

In [ ]:
"""
线性回归的基本要素：
1. 模型定义
2. 模型训练
    （1）训练数据
    （2）损失函数
    （3）优化算法
3. 模型预测   
"""

In [ ]:
"""
线性回归的表示方法：
1. 神经网络图
2. 矢量计算表达式：尽可能地采用矢量计算，可以提升计算效率
"""

In [ ]:
################详细内容#############################

In [ ]:
"""
线性回归的基本要素：
1. 模型定义：y_hat = x1*w1 + x2 *w2 + b
    其中w1和w2是权重，b是偏差，且均为标量，它们是线性回归模型的参数
2. 模型训练：通过数据来寻找特定的模型参数值
    （1）训练数据：训练数据集(training data set)或训练集(training set);
        一栋房屋被称为一个样本(sample), 其真实售价叫做标签(label),用来
        预测标签的两个因素叫作特征(feature).特征用来表征样本的特点。
    （2）损失函数：在模型训练中，我们需要衡量价格预测值和真实值之间的误差。
        通常我们会选取一个非负数作为误差，且数值越小表示误差越小。一个常用
        的选择是平方函数。给定训练数据集，这个误差只与模型参数有关。因此我们将
        它记为以模型参数为参数的函数。 在机器学习中，将衡量误差的函数称为损失函数
        （loss function）。 这里使用的平方误差函数也称为平方损失(square loss)
    （3）优化算法
3. 模型预测   
"""

In [2]:
import torch
import numpy as np
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.randn(num_examples, num_inputs, dtype=torch.float32)
labels = true_w[0] * features[:,0] + true_w[1]*features[:,1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float32)


In [3]:
features

tensor([[-9.6893e-02,  2.6896e+00],
        [-9.0121e-02,  1.5912e-03],
        [-4.7187e-01,  3.2006e-01],
        ...,
        [-2.2354e+00, -1.4104e+00],
        [-8.2103e-01,  1.8168e+00],
        [ 1.6786e-01, -8.3239e-01]])

In [7]:
features.shape

torch.Size([1000, 2])

In [5]:
labels.shape

torch.Size([1000])

In [6]:
labels

tensor([-5.1239e+00,  4.0151e+00,  2.1636e+00,  3.9438e+00, -2.1678e+00,
         5.1370e+00, -5.0305e-01,  2.3500e+00,  9.4857e+00,  1.0978e+01,
         3.2044e+00,  3.8381e+00,  3.7091e+00,  5.5447e-01,  3.9363e+00,
         9.8966e-01,  4.6488e+00,  8.8028e+00,  7.3386e+00,  1.5945e+01,
         6.4379e+00,  9.7523e+00,  2.8910e+00,  4.4506e+00,  1.0251e+01,
         1.6766e+00,  9.5454e+00,  8.7712e+00,  1.2965e+01,  6.2491e+00,
         3.8255e+00,  1.2281e+01,  3.2730e-01, -2.9068e+00, -9.6123e-01,
         5.8793e+00,  1.1313e+01,  3.4174e+00,  3.7233e+00,  4.4722e+00,
        -9.5606e-01,  2.1057e+00,  3.0271e+00,  1.0315e+01,  6.1492e+00,
         5.2117e+00,  1.5836e+00, -5.0695e+00, -3.0314e+00, -2.7989e+00,
         2.8826e+00,  8.7523e-01,  7.4351e+00,  5.0063e+00,  6.1609e+00,
         1.0901e+01,  2.5797e+00, -2.1531e-01,  8.9525e+00, -5.5177e-01,
         1.1527e+01,  7.9674e+00,  7.8989e+00,  8.0528e+00,  5.5912e+00,
         5.7513e+00,  5.9662e+00,  1.3710e+01,  6.4

In [4]:
import torch
import numpy as np
w = torch.tensor(np.random.normal(0, 0.01, (10,1)), dtype=torch.float32)


In [5]:
w

tensor([[-1.1115e-02],
        [ 1.7759e-02],
        [-5.3435e-03],
        [-6.7920e-03],
        [ 1.8215e-02],
        [-2.2765e-02],
        [-7.3806e-03],
        [-3.3257e-02],
        [ 6.2405e-03],
        [ 8.4125e-05]])

In [6]:
b = torch.zeros(1,dtype=torch.float32)

In [7]:
b

tensor([0.])